### ISSUE TITLE
ZB Firmware OTA - Invalid Signature

### ISSUE THREAD

**Issue by NeoMatrixJR** [vahempio/Tasmota-for-eWeLink#3] opened 2022-04-25 18:31 UTC
Attempted to flash zigbee firmware (.ota) from file and I get invalid file signature....
![image](https://user-images.githubusercontent.com/24440026/165151758-c501c02a-ff53-4920-94aa-824731fe4f87.png)

**Comment by vahempio** [comment] 2022-04-25 19:23
Very strange, seems that your file is not correct. Can you check that the sha256sum on the file has the following value: 
a9083c2d2461a805a4a090c2f0ad4f1ea763d4efd60289750fd99935fd2f4c49
Thanks

**Comment by NeoMatrixJR** [comment] 2022-04-25 21:16
The NSW file I downloaded matches that.  I've also tried the SW file.  Both fail.

**Comment by NeoMatrixJR** [comment] 2022-04-26 01:30
I just pulled a copy of your bin file from the bin folder when I flashed...is that the right tasmota to flash for this?

**Comment by NeoMatrixJR** [comment] 2022-04-27 04:23
Interestingly...I get no ZIG lines as described here (https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html) in my logs... But I'm pretty sure I have a firmware already flashed...I had this working (more or less) with the ESPHome firmware prior to loading this.  I don't think changing the ESP firmware should have caused any issues with the zigbee firmware....
>00:00:00.002 HDW: ESP32-D0WDQ6-V3 
00:00:00.003 HDW: FoundPSRAM=0 CanUsePSRAM=0
00:00:00.025 UFS: FlashFS mounted with 44 kB free
00:00:00.067 CFG: Loaded from File, Count 45
00:00:00.069 CFG: CR 436/699, Busy 0
00:00:00.074 ROT: Mode 1
00:00:00.075 BRY: GC from 1418 to 1418 bytes, objects freed 0/1 (in 1 ms)
00:00:00.083 BRY: GC from 3621 to 3043 bytes, objects freed 5/29 (in 0 ms)
00:00:00.116 BRY: GC from 4409 to 3849 bytes, objects freed 3/47 (in 0 ms)
00:00:00.116 BRY: Berry initialized, RAM used=3849
00:00:00.129 BRY: no 'preinit.be'
00:00:00.132 SRC: Restart
00:00:00.135 Project tasmota - ZB-GW3 Version 10.1.0(tasmota)-2_0_1_1(2021-12-18T19:06:37)
00:00:01.501 ETH: Attempting connection...
00:00:01.502 ETH: Connected at 100Mbps Full Duplex
00:00:01.555 TCP: from MCU: 7697B5A9772A14B314B65CFCA1AB6D1E285A236E197E0697B1A9702A58904F4D41DB5502265D9C4D27AB0A587E5E97B5A9772A14B314B65CFCA1AB6D1E285A239E9D7E6E97B1A9702A58904F4D41DB5502265D9C4D27ABDC2A7E7D5E97B5A9772A14B314B65CFCA1AB6D1E285A23FE277E0E97B1A9702A58904F4D41DB5502265D9C4D27ABB7E17E
00:00:01.627 BRY: no 'autoexec.be'
00:00:02.428 TCP: from MCU: 5E97B5A9772A14B314B65CFCA1AB6D1E285A239E9D7E6E97B1A9702A58904F4D41DB5502265D9C4D27ABDC2A7E7D5E97B5A9772A14B314B65CFCA1AB6D1E285A23FE277E0E97B1A9702A58904F4D41DB5502265D9C4D27ABB7E17E
00:00:03.503 ETH: Disconnected
00:00:03.828 TCP: from MCU: 1697B5A9772A14B314B65CFCA1AB6D1E285A23CFD77E
00:00:05.628 TCP: from MCU: C20251A8BD7E
00:00:07.503 ETH: Connected at 100Mbps Full Duplex
00:00:07.506 ETH: Mac 94:B9:7E:D3:50:27, IPAddress 192.168.5.65, Hostname taz-zb-gw3-4132-eth
00:00:07.930 NTP: Synch time...
00:00:08.087 RTC: UTC 2022-04-27T04:20:04, DST 2022-03-27T02:00:00, STD 2022-10-30T03:00:00
05:20:04.000 NTP: Synched
05:20:04.062 HTP: Web server active on taz-zb-gw3-4132-eth with IP address 192.168.5.65
05:20:05.145 MQT: Attempting connection...
05:20:05.155 MQT: Connected
05:20:05.158 MQT: tele/taz_zb-gw3/LWT = Online (retained)
05:20:05.166 MQT: cmnd/taz_zb-gw3/POWER = 
05:20:05.167 MQT: Subscribe to cmnd/taz_zb-gw3/#
05:20:05.169 MQT: Subscribe to cmnd/tasmotas/#
05:20:05.171 MQT: Subscribe to cmnd/Taz_ZBGW_fb/#
05:20:05.174 MQT: Unsubscribe from homeassistant/status
05:20:05.179 MQT: tele/taz_zb-gw3/INFO1 = {"Info1":{"Module":"ZHA-bridge","Version":"10.1.0(tasmota)","FallbackTopic":"cmnd/Taz_ZBGW_fb/","GroupTopic":"cmnd/tasmotas/"}}
05:20:05.186 MQT: tele/taz_zb-gw3/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"taz-zb-gw3-4132-eth","IPAddress":"192.168.5.65"}}
05:20:05.192 MQT: tele/taz_zb-gw3/INFO3 = {"Info3":{"RestartReason":"Software reset CPU"}}
05:20:05.199 TFS: File 'autoexec.bat' not found
05:20:05.209 RUL: SYSTEM#BOOT performs "TCPStart 8888"
05:20:05.209 SRC: Rule
05:20:05.210 CMD: Grp 0, Cmnd 'TCPSTART', Idx 1, Len 4, Data '8888'
05:20:05.212 TCP: Starting TCP server on port 8888
05:20:05.216 MQT: stat/taz_zb-gw3/RESULT = {"TCPStart":"Done"}
05:20:05.222 RUL: SYSTEM#BOOT performs "Wifi 0"
05:20:05.223 SRC: Rule
05:20:05.224 CMD: Grp 0, Cmnd 'WIFI', Idx 1, Len 1, Data '0'
05:20:05.228 MQT: stat/taz_zb-gw3/RESULT = {"Wifi":"OFF","Mode":"11 "}
05:20:05.254 HTP: Main Menu
05:20:05.914 APP: Boot Count 12
05:20:06.957 CFG: Saved, Count 46, Bytes 4096
05:20:09.929 BRY: GC from 5547 to 3710 bytes, objects freed 17/48 (in 1 ms)
05:20:09.933 MQT: tele/taz_zb-gw3/STATE = {"Time":"2022-04-27T05:20:09","Uptime":"0T00:00:13","UptimeSec":13,"Heap":176,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":48}}
05:20:09.943 MQT: tele/taz_zb-gw3/SENSOR = {"Time":"2022-04-27T05:20:09","ESP32":{"Temperature":53.3},"TempUnit":"C"}
05:20:14.941 MQT: tasmota/discovery/94B97ED35024/config = {"ip":"0.0.0.0","dn":"ZB-GW3","fn":["ZB-GW3",null,null,null,null,null,null,null],"hn":"taz-zb-gw3-4132","mac":"94B97ED35024","md":"ZHA-bridge","ty":0,"if":0,"ofln":"Offline","onln":"Online","state":["OFF","ON","TOGGLE","HOLD"],"sw":"10.1.0","t":"taz_zb-gw3","ft":"%prefix%/%topic%/","tp":["cmnd","stat","tele"],"rl":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"swc":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"swn":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"btn":[0,0,0,0,0,0,0,0],"so":{"4":0,"11":0,"13":0,"17":0,"20":0,"30":0,"68":0,"73":0,"82":0,"114":0,"117":0},"lk":0,"lt_st":0,"sho":[0,0,0,0],"ver":1} (retained)
05:20:14.948 MQT: tasmota/discovery/94B97ED35024/sensors = {"sn":{"Time":"2022-04-27T05:20:14","ESP32":{"Temperature":53.3},"TempUnit":"C"},"ver":1} (retained)
05:20:53.932 TCP: Got connection from 192.168.5.25

**Comment by NeoMatrixJR** [comment] 2022-04-27 04:59
is this right? I see others say 75...but I'm not sure if that's only for the sonoff bridge.
![image](https://user-images.githubusercontent.com/24440026/165443794-f5fd29b8-e796-4773-9833-a220529cd6ec.png)

**Comment by vahempio** [comment] 2022-04-28 06:15
Can you confirm me that you are using an eWeLink bridge and the hw rev is 1.3? (Information is on the PCB)
I'm trying to reproduce, and will post screenshots step by step for comparison.

**Comment by vahempio** [comment] 2022-04-28 06:17
> is this right? I see others say 75...but I'm not sure if that's only for the sonoff bridge. ![image](https://user-images.githubusercontent.com/24440026/165443794-f5fd29b8-e796-4773-9833-a220529cd6ec.png)

Your screen is correct. Here is mine (but on my local dev branch, that is why I'm with 11.0.0)
![Screenshot_20220428-081621_Chrome](https://user-images.githubusercontent.com/37039929/165689258-69e77990-3583-464c-a22c-a1d57a1d3852.jpg)

**Comment by NeoMatrixJR** [comment] 2022-05-04 17:41
Sorry, I haven't been able to respond recently.  Yes it's the 1.3 version
![image](https://user-images.githubusercontent.com/24440026/166746959-09540e9e-7f8c-4878-9e1b-11ccdd661e05.png)
![image](https://user-images.githubusercontent.com/24440026/166747033-10cae8a8-f835-4698-a78d-ff712c65251c.png)

**Comment by NeoMatrixJR** [comment] 2022-05-05 05:20
Got it re-flashed with your bin using USB/Serial...got it to update the zigbee firmware.  For some reason I still have trouble with it just...stopping.  Trying to find out if it's the controller...Z2M or what.  At some point it just....stops getting updates from sensors. :(

**Comment by vahempio** [comment] 2022-05-05 19:32
Ok, thanks for the HW version confirmation.
After many tests, I reproduced the "invalid file signature": this appends when the current template is not correct.
(if you copy/paste lines, be carreful by carriage return in Github, in case of)

In order to start from a perfect fresh setup, here is steps to follow, and be sure that everything is aligned:
1/ I use [Tasmota online](https://tasmota.github.io/install/) with default firmware + "erase memory" option
2/ Setup your WiFi credentials, and observe that your are in version `11.1.0` (or later)
3/ Upgrade with the `tasmota32-EWELINK.bin` file. Observe that you are now in version `10.1.0`
4/ Reset all settings (for memory erase), re-enter your WiFi credentials
5/ In the shell command: `backlog Template {"NAME":"ZB-GW03-V1.3","GPIO":[0,0,3552,0,3584,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,608,640,32,0,0,0,0,0],"FLAG":0,"BASE":1} ; module 0`
5.1/ You should see LEDs activity (green & red) at this point
6/ Upgrade with the `ncp-uart-sw-6.7.9_115200.ota` file
7/ In the shell command: `backlog template {"NAME":"ZHA-bridge","GPIO":[0,0,5472,0,5504,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,608,640,32,0,0,0,0,0],"FLAG":0,"BASE":1} ; module 0`
8/ Wait the reboot, and again in the shell command: `backlog rule1 on system#boot do TCPStart 8888 endon ; rule1 1 ; tcpstart 8888`
9/ Enjoy with Home Assistant!

I have made many tests, and this is quite robust, you should have a clean setup after these steps. Let me know!

**Comment by NeoMatrixJR** [comment] 2022-05-06 01:58
Got that to work...sadly still getting a lot of lag/pausing of commands.  So...it's not a firmware issue :(

**Comment by vahempio** [comment] 2022-05-07 16:25
Ok, thanks for your feedback.
Last chance, I have uploaded a new firmware, aligned of the lastest stable version of tasmota (v11.1.0), available in the repository with the file [bin/tasmota32-EWELINK_11.1.0.bin](https://github.com/vahempio/Tasmota-for-eWeLink/blob/ewelink-eth/bin/tasmota32-EWELINK_11.1.0.bin).
I close the issue due to our same conclusion, this seems to be an hardware problem here.

**Closed as completed by vahempio** 2022-05-07 16:25 UTC
